version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.vue
    ports:
      - "80:80"
